title: "Aura Teasley"
email: aura.teasley@my.utsa.edu
description: >- # this means to ignore newlines until "baseurl:"
  Howdy!
baseurl: "/" 
url: "https://Aura-Buddy.github.io" 
twitter_username: mlhacks
github_username:  mlh-fellowship

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
